Sam_exp
bcgov/bcgovr pull request #4
Opened 2017-07-24 22:04 UTC by boshek

- Removed rstudioapi:: functions for now pending next CRAN release of rstudioapi
- Tidied up the messages that are generated when a user create an analysis/package
- Added a RBuildignore file that is more suitable to bcgov package
- Expanded the README. @ateucher and @stephhazlitt - would appreciate a read through this to ensure clarity and readability.

2017-07-24 22:06 UTC, boshek commented
Closes #2

2017-07-24 22:20 UTC, ateucher requested changes
Looks great @boshek! I wonder if we can rely more heavily on devtools for the `package_skeleton` and then build on that... But I think we can merge this as it's definitely better, then we can tackle the broader questions.

I think the only thing that needs fixing is replacing `tryCatch`.

2017-07-24 22:20 UTC, ateucher commented on R/analysis_skeleton.R
> +  if (path != ".") tryCatch(dir.create(path, recursive = TRUE),
Can do `dir.create(path, recursive = TRUE, showWarnings = FALSE)` here instead of tryCatch

2017-07-24 22:20 UTC, ateucher commented on R/package_skeleton.R
> +  if (path != ".") tryCatch(dir.create(path, recursive = TRUE),
Same as above with `showWarnings = FALSE`

2017-07-24 22:20 UTC, ateucher commented on R/package_skeleton.R
> +  devtools::setup(npath, rstudio = FALSE)
Can we use `rstudio = TRUE` here and rely on devtools' Rproj infrastructure?

2017-07-24 22:20 UTC, ateucher commented on R/package_skeleton.R
> +  if (rstudio) {
See question above

2017-07-24 22:20 UTC, ateucher commented on R/package_skeleton.R
> +  add_rbuildignore(npath)
Should we append bcgov stuff to the .Rbuildignore created by `devtools::setup` rather than build our own?

2017-07-24 22:35 UTC, boshek commented on R/analysis_skeleton.R
> +  if (path != ".") tryCatch(dir.create(path, recursive = TRUE),
Fixed by: 44c91c9

2017-07-24 22:35 UTC, boshek commented on R/package_skeleton.R
> +  if (path != ".") tryCatch(dir.create(path, recursive = TRUE),
Fixed by: 44c91c9

2017-07-24 22:55 UTC, ateucher approved these changes

2017-07-24 23:16 UTC, boshek commented on R/package_skeleton.R
> +  devtools::setup(npath, rstudio = FALSE)
Addressed by: db5c537

2017-07-24 23:16 UTC, boshek commented on R/package_skeleton.R
> +  add_rbuildignore(npath)
Addressed by: db5c537

2017-07-24 23:16 UTC, boshek commented on R/package_skeleton.R
> +  if (rstudio) {
Addressed by: db5c537

2017-07-24 23:26 UTC, ateucher commented on R/package_skeleton.R
> +  devtools::setup(npath, rstudio = TRUE, description = bcgovr_desc)
Should this rely on the value of `rstudio` passed into `package_skeleton`?

2017-07-24 23:40 UTC, boshek commented on R/package_skeleton.R
> +  devtools::setup(npath, rstudio = TRUE, description = bcgovr_desc)
I wonder if the more relevant question is: can you think of an instance where you are creating a package and wouldn't require .Rproj file? If you can then I will certainly make this change. If not though then maybe the rstudio and the description_template argument should both just be removed?

2017-07-24 23:43 UTC, ateucher commented on R/package_skeleton.R
> +  devtools::setup(npath, rstudio = TRUE, description = bcgovr_desc)
Only that not everyone uses RStudio... although the number of those that don't is getting smaller

2017-07-24 23:46 UTC, boshek commented on R/package_skeleton.R
> +  devtools::setup(npath, rstudio = TRUE, description = bcgovr_desc)
You're right. Will add in.

2017-07-24 23:53 UTC, boshek commented on R/package_skeleton.R
> +  devtools::setup(npath, rstudio = TRUE, description = bcgovr_desc)
Fixed by: bcc0b64

2017-07-25 00:10 UTC, ateucher commented
LGTM! I say merge whenever you're ready

2017-07-25 14:57 UTC, merged